project_id = "duqpnawfzihqbyttcrvk"

[functions.carson-chat]
verify_jwt = false

[functions.execute-workflow]
verify_jwt = false

[functions.lantid-chat]
verify_jwt = false

[functions.nerve-center]
verify_jwt = false
